In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[0][0]

In [4]:
X

array([[8],
       [8]])

In [5]:
y

1

In [6]:
# This function calculates sigmoid activation function
class sigmoid:

    def __init__(self,m):
        self.m = m
        self.use_sigmoid()

    def use_sigmoid(self):
        sig = np.where(self.m >= 0,1/(1 - np.exp(-self.m)),np.exp(self.m)/(np.exp(-self.m) - 1))
        return sig
        #if self.m >= 0:
            #return 1/(1 - np.exp(-self.m))
        #else:
            #return np.exp(self.m)/(np.exp(-self.m) - 1)


# This function calculates tanh activation function
class tanh:

    def __init__(self,m):
        self.m = m
        self.use_tanh()

    def use_tanh(self):
        z = (np.exp(self.m) - np.exp(-self.m))/(np.exp(self.m) + np.exp(-self.m))
        return z



# This function calculates relu activation function
class relu:

    def __init__(self, m):
        self.m = m
        self.use_relu()

    def use_relu(self):
        if np.all(self.m > 0):
            return self.m
        else:
            return 0



# This function calculates softmax activation function
class softmax:

    def __init__(self, m):
        self.m = m
        self.use_softmax()

    def use_softmax(self):
        x = np.copy(self.m)
        max_exp = np.max(x)

        x = np.exp(x - max_exp)
        x = x / np.sum(x)

        return x



# This function call different activation function
class apply_activation:

    def __init__(self, activation_function, value):
        self.activation_function = activation_function.lower()
        self.value = value
        self.do_activation()


    def do_activation(self):
        if self.activation_function == 'sigmoid':
            return sigmoid(self.value).use_sigmoid()
        elif self.activation_function == 'relu':
            return relu(self.value).use_relu()
        elif self.activation_function == 'tanh':
            return tanh(self.value).use_tanh()
        elif self.activation_function == 'softmax':
            return softmax(self.value).use_softmax()



class sigmoid_derv:

    def __init__(self,m):
        self.m = m
        self.sigmoid_d()

    def sigmoid_d(self):
        sig_d = np.where(self.m >= 0,1/(1 - np.exp(-self.m)),np.exp(self.m)/(np.exp(-self.m) - 1))
        return sig_d * (1 - sig_d)



class relu_derv:

    def __init__(self,m):
        self.m = m
        self.relu_d()

    def relu_d(self):
        if self.m > 0:
            return 1
        else:
            return 0



class tanh_derv:

    def __init__(self,m):
        self.m = m
        self.tanh_d()

    def tanh_d(self):
        z = (np.exp(self.m) - np.exp(-self.m))/(np.exp(self.m) + np.exp(-self.m))
        return (1 - (z)**2)





class apply_activation_derivative:

    def __init__(self,activation_function, value):
        self.activation_function = activation_function.lower()
        self.value = value
        self.do_activation_derivative()

    def do_activation_derivative(self):
        if self.activation_function == 'sigmoid':
            return sigmoid_derv(self.value).sigmoid_d()
        elif self.activation_function == 'relu':
            return relu_derv(self.value).relu_d()
        elif self.activation_function == 'tanh':
            return tanh_derv(self.value).tanh_d()




In [27]:
import numpy as np

class crossentropy:

    def __init__(self, y, y_predicted):
        self.y = y
        self.y_predicted = y_predicted
        self.give_celoss()

    def give_celoss(self):
        threshold = 10**(-8)
        res = -np.sum(np.sum(self.y*np.log(self.y_predicted)))
        return res

class squarderror:

    def __init__(self, y, y_predicted):
        self.y = y
        self.y_predicted = y_predicted
        self.give_seloss()

    def give_seloss(self):
        res = np.sum((self.y - self.y_predicted)**2)
        return np.sum(res)


class callloss:

    def __init__(self,loss_function, value1, value2):
        self.loss_function = loss_function.lower()
        self.value1 = value1
        self.value2 = value2
        self.give_loss()

    def give_loss(self):
        if self.loss_function == 'ce':
            return crossentropy(self.value1, self.value2).give_celoss()
        if self.loss_function == 'se':
            return squarderror(self.value1, self.value2).give_seloss()

class crossentropy_grad:

    def __init__(self,y ,y_predicted):
        self.y = y
        self.y_predicted = y_predicted
        self.Give_cegrad()

    def Give_cegrad(self):
        grad = -self.y/(self.y_predicted)
        return grad


class squarederror_grad:

    def __init__(self,y , y_predicted):
        self.y = y
        self.y_predicted = y_predicted
        self.Give_segrad()

    def Give_segrad(self):
        res = -np.sum(self.y - self.y_predicted)
        return res

class call_lossgrad:

    def __init__(self,loss_function, value1, value2):
        self.loss_function = loss_function.lower()
        self.value1 = value1
        self.value2 = value2
        self.give_gradloss()

    def give_gradloss(self):
        if self.loss_function == 'ce':
            return crossentropy_grad(self.value1, self.value2).Give_cegrad()
        if self.loss_function == 'se':
            return squarederror_grad(self.value1, self.value2).Give_segrad()

In [55]:
import numpy as np

class Initilize:

    def __init__(self, i_size, o_size, method = "Xavier_U"):
        self.i_size = i_size
        self.o_size = o_size
        self.w, self.b = self.Init_weight(method)

    def Init_weight(self, init_method):


        if init_method == "Xavier_N":
          np.random.seed(0)
          a = np.sqrt(1 / self.i_size)
          w = np.random.randn(self.i_size,self.o_size)*a

        elif init_method == "Xavier_U":
          np.random.seed(0)
          a = np.sqrt(6 / (self.o_size + self.i_size))
          w = np.random.uniform((-a), a,( self.i_size, self.o_size))

        elif init_method == "He_N":
          np.random.seed(0)
          a = np.sqrt(2 / self.i_size)
          w = np.random.randn(self.i_size, self.o_size)*a

        elif init_method == "He_U":
          np.random.seed(0)
          a = np.sqrt(6 / self.i_size)
          w = np.random.uniform(-a, a, (self.i_size, self.o_size))

        elif init_method == "Random":
          np.random.seed(0)
          w = np.random.randn(self.i_size, self.o_size)*0.01

        b = np.zeros((self.o_size,1))

        return w, b




class Weight_bias:
  def __init__(self, layer_dimension, activation_fn, method):
    self.n = layer_dimension
    self.activation_fn = activation_fn
    self.method = method

  def Init_network(self, layer_dimension):
    self.n = layer_dimension
    self.network = {}

    for i in range(1, len(self.n)):
      self.network["w" + str(i)] = Initilize(self.n[i-1], self.n[i], self.method).Init_weight(self.method)[0]
      self.network["b" + str(i)] = Initilize(self.n[i-1], self.n[i], self.method).Init_weight(self.method)[1]
      self.network ["h"+ str(i)] = str(self.activation_fn[i-1])
      self.network ["neuronns in layer "+ str(i)] = self.n[i]

    return self.network



class Pre_Feedforward:

  def __init__(self, Prev_layer_H, w, b, activation_fn):
    self.Prev_layer_H= Prev_layer_H
    self.w = w
    self.b = b
    self.activation_fn = activation_fn
    self.Preactivation_cal()


  def Preactivation_cal(self):

    A = np.dot(self.w.T, self.Prev_layer_H) + self.b
    H = apply_activation(self.activation_fn, A).do_activation()
    cache = (self.Prev_layer_H, A)
    #self.cache["Input"] = self.Prev_layer_H
    #self.cache["Pre_act"] = H
    return cache , H

class Feedforward:

  def __init__(self,X_train, layer_dimension, activation_fn, method):
    self.X_train = X_train
    self.n = layer_dimension
    self.activation_fn = activation_fn
    self.method = method


  def Forward_prop(self):
    network = Weight_bias(self.n, self.activation_fn,self.method).Init_network(self.n)
    H = self.X_train
    L = len(self.n) - 1
    Inter_layers = {}

    for i in range(1,L+1):
      Prev_layer_H = H

      w_l = network["w"+  str(i)]
      b_l = network["b"+  str(i)]
      Act_fn_l = network["h" + str(i)]

      cache, H = Pre_Feedforward(Prev_layer_H, w_l,b_l,Act_fn_l).Preactivation_cal()


      #A = np.dot(w_l.T, Prev_layer_H) + b_l
      #H = apply_activation(Act_fn_l, A).do_activation()

      Inter_layers["h" + str(i-1)] = cache[0]
      Inter_layers["a" + str(i)] = cache[1]
      #cache.append((Prev_layer_H, A))

      #cache , New_H = Pre_Feedforward(Prev_layer_H, w_l, b_l, Act_fn_l).Preactivation_cal()
      #cache.appand()

    return cache,Inter_layers,network , H


class Findloss:
  def __init__(self,X_train, y_train, layer_dimension, activation_fn, method, loss_function):
    self.X_train = X_train
    self.y_train = y_train
    self.n = layer_dimension
    self.activation_fn = activation_fn
    self.loss_function = loss_function
    self.method = method
    self.y_pred = Feedforward(self.X_train, self.n, self.activation_fn, self.method).Forward_prop()[-1]

  def loss(self):
    return callloss(self.loss_function, self.y_train, self.y_pred).give_loss()

In [56]:
class Backprop:

  def __init__(self, X_train ,y_train, layer_dimension,activation_fn,grad_activation_fn, method,loss_function, grad_loss_function):

    self.X_train = X_train
    self.y_train = y_train
    self.n = layer_dimension
    self.activation_fn = activation_fn
    self.grad_activation_fn = grad_activation_fn
    self.loss_function = loss_function
    self.method = method
    self.grad_loss_function = grad_loss_function

  def Backpropagation(self):

    y_pred = Feedforward(self.X_train, self.n, self.activation_fn, self.method).Forward_prop()[-1]
    loss = Findloss(self.X_train, self.y_train, self.n, self.activation_fn, self.method, self.loss_function).loss()

    L = len(self.n)

    grad_L_yhat = call_lossgrad(self.loss_function, y_train, y_pred).give_gradloss()
    grad_yhat_a_L = grad_L_yhat *

    for i in range()



SyntaxError: expected ':' (<ipython-input-56-fcc5a8ffadee>, line 16)

In [60]:
Findloss(X,y,[2,3,2,1], ['sigmoid','sigmoid','softmax'],"Xavier_U","se").loss()

0.0

In [58]:
y

1

In [62]:
Feedforward(X,[2,3,1],['sigmoid','sigmoid','sigmoid','softmax'],"Xavier_U").Forward_prop()

((array([[1.23999836],
         [1.09616172],
         [1.01296675]]),
  array([[0.98103753]])),
 {'h0': array([[8],
         [8]]),
  'a1': array([[1.64223325],
         [2.43353861],
         [4.35825011]]),
  'h1': array([[1.23999836],
         [1.09616172],
         [1.01296675]]),
  'a2': array([[0.98103753]])},
 {'w1': array([[ 0.10694503,  0.47145628,  0.22514328],
         [ 0.09833413, -0.16726395,  0.31963799]]),
  'b1': array([[0.],
         [0.],
         [0.]]),
  'h1': 'sigmoid',
  'neuronns in layer 1': 3,
  'w2': array([[0.11956818],
         [0.52710415],
         [0.25171784]]),
  'b2': array([[0.]]),
  'h2': 'sigmoid',
  'neuronns in layer 2': 1},
 array([[1.5998001]]))

In [ ]:
Initilize(3,5,"Xavier_N").Init_weight("Xavier_N")

In [ ]:
x = [relu,relu,sigmoid]
print(x[1])

In [ ]:
Weight_bias([4,2,3,1],['relu','relu','sigmoid'],"Xavier_N").Init_network([4,2,3,1])